### ISSUE TITLE
Sequence should not tick previous children if a children returns Running

### ISSUE THREAD

**Issue by JonPichel** [joeycumines/go-behaviortree#11]
Hi, I have recently started using this library and I wanted to thank you for the amazing work.

I have the following BT. The logic I am trying to implement is making the ship extract resources and sell those not wanted until full. The extract resources action has a cooldown so its sibling node first checks if the cooldown is active and returns running if so:

```
	return bt.New(bt.Sequence,
		Sell(ship, sellExceptions...),
		bt.New(bt.Sequence,
			bt.New(func(children []bt.Node) (bt.Status, error) {
				if time.Now().Before(ship.Cooldown.Expiration) {
					return bt.Running, nil
				}
				if ship.Cargo.Units == ship.Cargo.Capacity {
					return bt.Failure, nil
				}
				return bt.Success, nil
			}),
			Extract(ship),
		),
	)
```

From what I understand about Behavior Trees, I expected the outer sequence node to directly Tick its second child (that is the inner Sequence node), since it returned a Running Status. Is this the expected behavior in your implementation? If so, how can I implement the behavior I described?

**Comment by joeycumines** [comment]
Hey @JonPichel :)

It sounds like you want to use either `bt.Memorize` or `bt.Sync`. I recommend the former - there are specific niche use cases for the `Sync` implementation, but `Memorize` is easiest to use.

It's a tick wrapper, so just changing `bt.Sequence` -> `bt.Memorize(bt.Sequence)` should achieve your desired outcome, unless I'm misunderstanding.
