### ISSUE TITLE
How to learn and use for beginners

### ISSUE THREAD

**Issue by erDong01** [joeycumines/go-behaviortree#5]

**Comment by joeycumines** [comment]
Hello @erDong01 :)

I'm happy to try to help with your question, but I will need a bit more detail.

What were you looking for specifically?

If it's code examples, some examples are provided in the repository.

If details about the higher level implementation / design, those are in the readme.

If it's an understanding of behavior trees, I'd point you at https://www.amazon.com/Behavior-Trees-Robotics-Introduction-Intelligence/dp/1138593737, available as a PDF at https://www.researchgate.net/publication/319463746_Behavior_Trees_in_Robotics_and_AI_An_Introduction .

My implementation aligns quite well with how behavior trees are presented in _Behavior trees in Robotics and AI: An Introduction_. If you're after a more practical introduction, you might have to poke around other projects. For example, https://www.behaviortree.dev/bt_basics/ / https://github.com/BehaviorTree/BehaviorTree.CPP/ .

The core functionality provided by this module is simple enough that I expect understanding the basic theory and a little practical experimentation is all that's needed.
